// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoReserva.Data;

namespace SoReserva.Migrations
{
    [DbContext(typeof(SoReservaContext))]
    [Migration("20220523170210_Booking e Vehicle")]
    partial class BookingeVehicle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("SoReserva.Models.Booking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Beginning")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NameOfVehicle")
                        .HasColumnType("text");

                    b.Property<DateTime>("Returning")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("id");

                    b.ToTable("Booking");
                });
#pragma warning restore 612, 618
        }
    }
}
